export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'core',
        'ui',
        'api',
        'db',
        'auth',
        'editor',
        'query',
        'schema',
        'connections',
        'export',
        'ai',
        'config',
        'deps',
      ],
    ],
    // Disabled strict rules
    'subject-case': [0],
    'body-max-line-length': [0],
    'header-max-length': [0],
  },
};
